POST http://localhost:3000/api/create-account HTTP/1.1
content-type: application/json

{
    "firstName": "Peter",
    "lastName": "Farmer",
    "email": "test@email.com",
    "displayName": "dynamo",
    "password": "test"
}

###
POST http://localhost:3000/api/create-account HTTP/1.1
content-type: application/json

{
    "firstName": "Daniel",
    "lastName": "Grayson",
    "email": "test2@email.com",
    "displayName": "Zeke",
    "phone": "0478618703",
    "password": "test2"
}